---
title: "Applied Time Series Projects"
subtitle: "Time Series Analysis"
format: html
# use quarto markdown to 
---



**Applied Time Series Research**

1. **China Export Commodities Time Series Analysis:**
   - Applied time series techniques to analyze trends, seasonality, and irregularities in China's export commodity data from 1990 to the present.
   - Conducted a classical multiplicative decomposition to distinguish long-term growth patterns, seasonal cycles, and random shocks influenced by macroeconomic events.
   - Provided actionable insights into optimizing trade strategies by leveraging seasonal trends and mitigating risks from unpredictable disruptions.  
- [Time Series Reserach on China's Export Commodities](/projects/project1.qmd)

2. **Consumer Credit Data Analysis:**
   - Examined consumer credit data from the G.19 Statistical Release, focusing on outstanding credit extended to individuals for household and personal expenditures.
   - Differentiated between revolving credit (e.g., credit card loans) and nonrevolving credit (e.g., motor vehicle and education loans) to identify distinct patterns and trends.
   - Analyzed the interest rates and terms of credit, including new car loans, personal loans, and credit card plans at commercial banks, and discussed the implications of historical data series.
   - Provided insights into consumer borrowing behaviors and the potential impact of macroeconomic changes on credit markets.
- [Project 2: Consumer Credit Data Analysis](/projects/project2.qmd)


3. **Project 3: Coming Soon**
- [project 3](/projects/project3.qmd)




