---
title: "Tools, Resources and Help Ideas"
subtitle: "draft"
format: html
# use quarto markdown to 
---


This page is to include pontential ideas to do for resources, tools, and ideas for time series


# individual yaml code

This will have many different options for yaml


**for individual qmd yaml code**

```
---
title: "Applied Time Series Analysis Notebook"
subtitle: "MATH 494R"
format: 
  html:
    self-contained: true # true: embeds all resources (CSS, image, etc) so it can be viewed offline (con: large file size) false: only html content is stored w/ external links to css, images etc. 
    page-layout: full
    error: false
    message: false
    warning: false
    embed-resources: true
    toc: false # overwrites project setting. cache must be clear or changes may not appear and/or errors will occur
    code-fold: true
    math: katex # katex, mathjax, none
    code-tools: # this is to show source code
      source: true 
      toggle: false
      caption: none
---

```

**For yaml website**

```
project: 
  type: website
  output-dir: docs 
  render:
    - "*.qmd" # renders all .qmd files
    - "!python.qmd" # using ! = ignores specific file
    - "!extras/" # ignores folder
    - "!readme.md" # ! can be use to ignore files and or folders

freeze: auto # not re render code if not change. 

website:
  title: "Statistics Notebook"
  favicon: Images/favicon.png
  back-to-top-navigation: true

  page-footer:
    border: true
    left: "Eduardo Ramirez 2024©"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/eduardo-ramirez-lds

  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Inference" # this section list names giving below only. it takes little space. name of navbar link is the one here "inference". 
        menu: # when the navbar name is click, the following names will show up
          - text: "Inference"  # this name will show up
            file: inference.qmd
          - text: "Distribution" # this name will show up
            file: inference/distribution.qmd
      - sidebar:describing_data

  sidebar: # required if using sidebar
    - id: describing_data 
      title: "Describing Data"
      style: "docked"
      collapse-level: 1
      contents:
        - graphicalsummaries.qmd
        - numericalsummaries.qmd

    - id: spacer # add id's as needed

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    fontsize: 0.9em # changes all fonts default is 1
    linestretch: 1 # default 1.5. affects distance between lines of text 
    css: styles.css
    toc: true # controls toc visibility. cache needs to be clear for indi qmd or project wide or errors can and will accur. 


```




# .yml code to fix

2.   back-to-top-navigation: true 
    * This is my original code and it works normally.
    * Time series uses this one: page-navigation: true 
      * When I use the time series I started getting this warning message
        * [WARNING] Could not fetch resource ../projects/project2.html
        * What is the difference between the two?
        

# using Definitons or footnotes

 The following is working code to use footnotes but works great for definitions. Obviously not the best way to reference def, but this seems like a simple and straight forward process. Seems super static so it wont take long to load as well.

White noise[^1]

[^1]: defintion here


# Streamline code

chapter_3_overview_code_draft.qmd is streamline

- Edits to variables happen in first code chunk and qmd runs all code for that chapter.

- May need to data frame set according to data


# color definitions 

so far I'm using the color purple for like definitions or the main topic of that paragraph but mostly definitions or explaining of a variable. 


I should make like a color code for the different colors I use.

- purple: purple is assign for variables or important subjects that are been define and or main topic of that paragraph and or just need to stand out. 

Pink: Pink will be assign to words that I don't know the definition and or meaning, and or words that need a definition link to them. This will help as I know that I can add the definition link later if I don't do it then






